server:
  port: 5000
spring:
  application:
    name: zhijia-crowd-project
  redis:
    host: 192.168.177.129
    password: qazwsx123
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka

aliyun:
  oss:
    end-point: http://oss-cn-shenzhen.aliyuncs.com
    access-key-id: LTAI5tGr5a9V16dbYkBfS6wn
    access-key-secret: 2A8itxxSoRH37tFXMNRm5w69wzXIDz
    bucket-name: zhijia1998
    bucket-domain: http://zhijia1998.oss-cn-shenzhen.aliyuncs.com

