server:
  port: 80
spring:
  application:
    name: zhijia-crowd-zuul
  redis:
    host: 192.168.177.129
    password: qazwsx123
  session:
    store-type: redis

eureka:
  client:
    #服务提供者provider注册进eureka服务列表内
    service-url:
      defaultZone: http://localhost:1000/eureka
zuul:
  ignored-services: "*"       #忽略原本微服务名称
  sensitive-headers: "*"      #向其他微服务重定向保持原来头信息
  routes:                     #自定义路由规则
    crowd-portal:             #自定义路由规则名称
      service-id: http://localhost:4000     #针对某服务设置路由规则
      path: /**
    crowd-project:
      service-id: http://localhost:5000     #针对某服务设置路由规则
      path: /project/**
    crowd-order:
      service-id: http://localhost:7000     #针对某服务设置路由规则
      path: /order/**
    crowd-pay:
      service-id: http://localhost:9000     #针对某服务设置路由规则
      path: /pay/**


#  cloud:
#    gateway:
#      routes:
#        - id: payment_routh              #路由ID，没有固定规则但要求统一
#          uri: http://localhost:4000     #匹配后提供服务的路由地址
#          predicates:
#            - Path=/**       #断言，路径相匹配的进行路由









