server:
  port: 7000
spring:
  application:
    name: zhijia-crowd-order

  redis:
    host: 192.168.177.129
    password: qazwsx123
  session:
    store-type: redis
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka


