server:
  port: 2000
spring:
  application:
    name: zhijia-crowd-mysql
  datasource:
    name: mydb
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://192.168.177.129:3306/project_crowd?serverTimeZone=UTC
    username: root
    password: '0000'
    driver-class-name: com.mysql.cj.jdbc.Driver
eureka:
  client:
    service-url:
      defaultZone: http://localhost:1000/eureka
mybatis:
  mapper-locations: classpath*:mybatis/mapper/*Mapper.xml
  type-aliases-package: com.zhijia.crowd.entity.po
logging:
  level:
    com.zhijia.crowd.mapper: debug
    com.zhijia.crowd.test: debug



